on:
  push:
    branches:
      - staging

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout staging
      uses: actions/checkout@v2

    - name: Update SHA
      run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/_meta

    - name: Build container image
      run: docker build -t registry.digitalocean.com/unicornariel1-container-registry/our_discord_server:$(echo $GITHUB_SHA | head -c7) .

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DOCTL_API_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600 -t ${{ secrets.DOCTL_API_TOKEN }}

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/unicornariel1-container-registry/our_discord_server:latest
